/**
 * Default reaction→audio tables keyed exclusively by {@link REACTION_PLAYBACK_PROFILE}.
 */

import { REACTION_PLAYBACK_PROFILE } from './reactionPlaybackProfiles.v1';

const DEFAULT_HANDS_RAISED_EQ = [8, 6, 3, 0, -2, -3];
const NODDING_MOUTH_OPEN_EQ = [0, 0, 8, 5, 3, 0];

export const DEFAULT_EQ_MAPPINGS = Object.freeze({
    [REACTION_PLAYBACK_PROFILE.NODDING_HAPPY]: [...DEFAULT_HANDS_RAISED_EQ],
    [REACTION_PLAYBACK_PROFILE.NODDING_MOUTH_OPEN]: [...NODDING_MOUTH_OPEN_EQ],
    [REACTION_PLAYBACK_PROFILE.NODDING_NEUTRAL]: [...DEFAULT_HANDS_RAISED_EQ],
    [REACTION_PLAYBACK_PROFILE.THUMB_DOWN]: [0, 0, 0, 0, 0, 0],
    [REACTION_PLAYBACK_PROFILE.THUMB_UP]: [0, 0, 0, 0, 0, 0],
    [REACTION_PLAYBACK_PROFILE.THUMB_UP_HANDS_RAISED]: [0, 0, 0, 0, 0, 0],
    [REACTION_PLAYBACK_PROFILE.THUMB_DOWN_HANDS_RAISED]: [0, 0, 0, 0, 0, 0],
    [REACTION_PLAYBACK_PROFILE.HANDS_RAISED]: [...DEFAULT_HANDS_RAISED_EQ],
    [REACTION_PLAYBACK_PROFILE.HAPPY]: [0, 0, 0, 0, 0, 0],
    [REACTION_PLAYBACK_PROFILE.MOUTH_OPEN]: [...NODDING_MOUTH_OPEN_EQ],
    [REACTION_PLAYBACK_PROFILE.NEUTRAL]: [0, 0, 0, 0, 0, 0],
});

export const DEFAULT_VOLUME_MAPPINGS = Object.freeze({
    [REACTION_PLAYBACK_PROFILE.NODDING_HAPPY]: 1.2,
    [REACTION_PLAYBACK_PROFILE.NODDING_MOUTH_OPEN]: 1.2,
    [REACTION_PLAYBACK_PROFILE.NODDING_NEUTRAL]: 1.2,
    [REACTION_PLAYBACK_PROFILE.THUMB_DOWN]: 1.0,
    [REACTION_PLAYBACK_PROFILE.THUMB_UP]: 1.0,
    [REACTION_PLAYBACK_PROFILE.THUMB_UP_HANDS_RAISED]: 1.0,
    [REACTION_PLAYBACK_PROFILE.THUMB_DOWN_HANDS_RAISED]: 1.0,
    [REACTION_PLAYBACK_PROFILE.HANDS_RAISED]: 1.45,
    [REACTION_PLAYBACK_PROFILE.HAPPY]: 1.0,
    [REACTION_PLAYBACK_PROFILE.MOUTH_OPEN]: 1.2,
    [REACTION_PLAYBACK_PROFILE.NEUTRAL]: 1.0,
});

export function resolveVolumeMultiplierForPlaybackProfile(volumeMappings, playbackProfile) {
    const raw = volumeMappings?.[playbackProfile];
    if (raw !== undefined && raw !== null) {
        const n = typeof raw === 'number' ? raw : parseFloat(raw);
        if (Number.isFinite(n)) return n;
    }
    return DEFAULT_VOLUME_MAPPINGS[playbackProfile] ?? 1.0;
}

export const DEFAULT_RHYTHMIC_ENHANCEMENT_MAPPINGS = Object.freeze({
    [REACTION_PLAYBACK_PROFILE.NODDING_HAPPY]: 0,
    [REACTION_PLAYBACK_PROFILE.NODDING_MOUTH_OPEN]: 100,
    [REACTION_PLAYBACK_PROFILE.NODDING_NEUTRAL]: 0,
    [REACTION_PLAYBACK_PROFILE.THUMB_DOWN]: 0,
    [REACTION_PLAYBACK_PROFILE.THUMB_UP]: 0,
    [REACTION_PLAYBACK_PROFILE.THUMB_UP_HANDS_RAISED]: 0,
    [REACTION_PLAYBACK_PROFILE.THUMB_DOWN_HANDS_RAISED]: 0,
    [REACTION_PLAYBACK_PROFILE.HANDS_RAISED]: 0,
    [REACTION_PLAYBACK_PROFILE.HAPPY]: 0,
    [REACTION_PLAYBACK_PROFILE.MOUTH_OPEN]: 100,
    [REACTION_PLAYBACK_PROFILE.NEUTRAL]: 0,
});

export const DEFAULT_REVERB_MAPPINGS = Object.freeze({
    [REACTION_PLAYBACK_PROFILE.NODDING_HAPPY]: 0,
    [REACTION_PLAYBACK_PROFILE.NODDING_MOUTH_OPEN]: 0,
    [REACTION_PLAYBACK_PROFILE.NODDING_NEUTRAL]: 0,
    [REACTION_PLAYBACK_PROFILE.THUMB_DOWN]: 0,
    [REACTION_PLAYBACK_PROFILE.THUMB_UP]: 0,
    [REACTION_PLAYBACK_PROFILE.THUMB_UP_HANDS_RAISED]: 0,
    [REACTION_PLAYBACK_PROFILE.THUMB_DOWN_HANDS_RAISED]: 0,
    [REACTION_PLAYBACK_PROFILE.HANDS_RAISED]: 0,
    [REACTION_PLAYBACK_PROFILE.HAPPY]: 0,
    [REACTION_PLAYBACK_PROFILE.MOUTH_OPEN]: 0,
    [REACTION_PLAYBACK_PROFILE.NEUTRAL]: 0,
});

export const DEFAULT_DELAY_MAPPINGS = Object.freeze({
    [REACTION_PLAYBACK_PROFILE.NODDING_HAPPY]: 0,
    [REACTION_PLAYBACK_PROFILE.NODDING_MOUTH_OPEN]: 0,
    [REACTION_PLAYBACK_PROFILE.NODDING_NEUTRAL]: 0,
    [REACTION_PLAYBACK_PROFILE.THUMB_DOWN]: 0,
    [REACTION_PLAYBACK_PROFILE.THUMB_UP]: 0,
    [REACTION_PLAYBACK_PROFILE.THUMB_UP_HANDS_RAISED]: 0,
    [REACTION_PLAYBACK_PROFILE.THUMB_DOWN_HANDS_RAISED]: 0,
    [REACTION_PLAYBACK_PROFILE.HANDS_RAISED]: 0,
    [REACTION_PLAYBACK_PROFILE.HAPPY]: 0,
    [REACTION_PLAYBACK_PROFILE.MOUTH_OPEN]: 0,
    [REACTION_PLAYBACK_PROFILE.NEUTRAL]: 0,
});

export const DEFAULT_KEY_SHIFT_MAPPINGS = Object.freeze({
    [REACTION_PLAYBACK_PROFILE.NODDING_HAPPY]: 0,
    [REACTION_PLAYBACK_PROFILE.NODDING_MOUTH_OPEN]: 0,
    [REACTION_PLAYBACK_PROFILE.NODDING_NEUTRAL]: 0,
    [REACTION_PLAYBACK_PROFILE.THUMB_DOWN]: 0,
    [REACTION_PLAYBACK_PROFILE.THUMB_UP]: 0,
    [REACTION_PLAYBACK_PROFILE.THUMB_UP_HANDS_RAISED]: 0,
    [REACTION_PLAYBACK_PROFILE.THUMB_DOWN_HANDS_RAISED]: 0,
    [REACTION_PLAYBACK_PROFILE.HANDS_RAISED]: 0,
    [REACTION_PLAYBACK_PROFILE.HAPPY]: 0,
    [REACTION_PLAYBACK_PROFILE.MOUTH_OPEN]: 0,
    [REACTION_PLAYBACK_PROFILE.NEUTRAL]: 0,
});

export function resolveKeyShiftForPlaybackProfile(keyShiftMappings, playbackProfile) {
    const v = keyShiftMappings?.[playbackProfile];
    if (v !== undefined && v !== null) return v;
    return DEFAULT_KEY_SHIFT_MAPPINGS[playbackProfile] ?? 0;
}

export const DEFAULT_BPM_SHIFT_MAPPINGS = Object.freeze({
    [REACTION_PLAYBACK_PROFILE.NODDING_HAPPY]: 0,
    [REACTION_PLAYBACK_PROFILE.NODDING_MOUTH_OPEN]: 0,
    [REACTION_PLAYBACK_PROFILE.NODDING_NEUTRAL]: 0,
    [REACTION_PLAYBACK_PROFILE.THUMB_DOWN]: 0,
    [REACTION_PLAYBACK_PROFILE.THUMB_UP]: 0,
    [REACTION_PLAYBACK_PROFILE.THUMB_UP_HANDS_RAISED]: 0,
    [REACTION_PLAYBACK_PROFILE.THUMB_DOWN_HANDS_RAISED]: 0,
    [REACTION_PLAYBACK_PROFILE.HANDS_RAISED]: 0,
    [REACTION_PLAYBACK_PROFILE.HAPPY]: 0,
    [REACTION_PLAYBACK_PROFILE.MOUTH_OPEN]: 0,
    [REACTION_PLAYBACK_PROFILE.NEUTRAL]: 0,
});
